---

 - name: Install NGINX
   hosts: all
   become: yes
   vars:
      nginx_listen_port: 8080

   tasks: 
     - name: Install EPEL repo packege from standart repo
       yum: 
         name: epel-release 
         state: installed
       tags:
         - epel-packege
         - packeges

     - name: Install NGINX
       yum: 
         name: nginx
         state: installed
       notify:
         - restart nginx
       tags:
         - nginx-package
         - packages
     - name: ensure nginx is the latest version
       yum:
         name: nginx
         state: latest
     - name: start nginx
       service:
         name: nginx
         state: started

     - name: NGINX create config file from templates
       template:
         src: nginx.conf.j2
         dest: /etc/nginx/nginx.conf
       notify:
         - reload nginx
       tags:
         - nginx-configuration
     
   handlers:
     - name: restart nginx
       systemd:
          name: nginx
          state: restarted
          enabled: yes
     - name: reload nginx
       systemd:
          name: nginx
          state: reloaded
